version: '3.8'
services:
  db:
    image: mysql
    container_name: 'craiyon-db'
    restart: always
    environment:
      - MYSQL_DATABASE=craiyon
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb: {}
